// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ1cG5LgEzAyvs53Ein8MsDrb7-4cL0MA',
    appId: '1:115160941920:web:16e06ad9d70ca8af930a05',
    messagingSenderId: '115160941920',
    projectId: 'fir-login-signup-14bf1',
    authDomain: 'fir-login-signup-14bf1.firebaseapp.com',
    storageBucket: 'fir-login-signup-14bf1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfxFyNbIgNdZE9qLb60ZK8YLmyu1YOMCA',
    appId: '1:115160941920:android:3d26ac2550518599930a05',
    messagingSenderId: '115160941920',
    projectId: 'fir-login-signup-14bf1',
    storageBucket: 'fir-login-signup-14bf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLFfcbU5djtRkcTKAJo7mrzTRMnumb_4',
    appId: '1:115160941920:ios:ca45bc5cd429b6d5930a05',
    messagingSenderId: '115160941920',
    projectId: 'fir-login-signup-14bf1',
    storageBucket: 'fir-login-signup-14bf1.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignmet7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLFfcbU5djtRkcTKAJo7mrzTRMnumb_4',
    appId: '1:115160941920:ios:ca45bc5cd429b6d5930a05',
    messagingSenderId: '115160941920',
    projectId: 'fir-login-signup-14bf1',
    storageBucket: 'fir-login-signup-14bf1.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignmet7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ1cG5LgEzAyvs53Ein8MsDrb7-4cL0MA',
    appId: '1:115160941920:web:6ac0f6da9e571eb1930a05',
    messagingSenderId: '115160941920',
    projectId: 'fir-login-signup-14bf1',
    authDomain: 'fir-login-signup-14bf1.firebaseapp.com',
    storageBucket: 'fir-login-signup-14bf1.firebasestorage.app',
  );
}
